version: '3.2'
services:
  elasticsearch:
   # image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    image: elasticsearch:5-alpine
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      #      - discovery.seed_hosts=elasticsearch
      #      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    build: .
    ports:
      - 9300:9300
      - 9200:9200
    restart: always

  kibana:
#    image: docker.elastic.co/kibana/kibana:7.15.2
    image: kibana:8.8.0
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9300"
    ports:
      - 5601:5601


  logstash:
    #image: docker.elastic.co/logstash/logstash:7.15.2
    image: logstash:5-alpine
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./config:/etc/logstash/conf.d
    ports:
      - "5000:5000"

volumes:
  esdata1:
    driver: local