POST http://localhost:8080/schools
Content-Type: application/json

{
  "name": "Vikrant's School"
}
###

POST http://localhost:8080/students
Content-Type: application/json

{
  "firstName": "Lisa",
  "lastName": "Simpson",
  "school": [
    "id" : 1
  ]
}
###

GET http://localhost:8080/schools
###

GET http://localhost:8080/students
###

GET http://localhost:8080/students/1
###

GET http://localhost:8080/schools/1

###

DELETE http://localhost:8080/students/1
###

DELETE http://localhost:8080/schools/1